apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/groupeinpt/garage-management-system-kubernetes.git
    targetRevision: HEAD
    path: customer
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vehicle-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/groupeinpt/garage-management-system-kubernetes.git
    targetRevision: HEAD
    path: vehicle
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/groupeinpt/garage-management-system-kubernetes.git
    targetRevision: HEAD
    path: workshop
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/groupeinpt/garage-management-system-kubernetes.git
    targetRevision: HEAD
    path: webapp
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/groupeinpt/garage-management-system-kubernetes.git
    targetRevision: HEAD
    path: gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/groupeinpt/garage-management-system-kubernetes.git
    targetRevision: HEAD
    path: rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: garage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

